steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "us-east1-docker.pkg.dev/notboring-447413/notboring/notboring:prod",
        ".",
      ]
options:
  logging: CLOUD_LOGGING_ONLY
