// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  contact: dynamic(() => import("./Contact")),
  hero_banner: dynamic(() => import("./HeroBanner")),
  partnership: dynamic(() => import("./Partnership")),
};
